from pathlib import Path

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PADDLE_WIDTH = 30
PADDLE_HEIGHT = 100
PADDLE_SPEED = 10

BALL_RADIUS = 10
BALL_SPEED = 15

BASE_PATH = Path(__file__).parent.parent.parent
